# This is the default errors
postgresql.arr.range:\u914D\u5217\u306E\u6DFB\u5B57\u306E\u5024\u304C\u6307\u5B9A\u53EF\u80FD\u306A\u7BC4\u56F2\u3092\u8D85\u3048\u3066\u3044\u307E\u3059\u3002
postgresql.drv.version:\u5185\u90E8\u30A8\u30E9\u30FC\u304C\u767A\u751F\u3057\u307E\u3057\u305F\u3002\u30C9\u30E9\u30A4\u30D0\u3092\u518D\u30B3\u30F3\u30D1\u30A4\u30EB\u3057\u3066\u304F\u3060\u3055\u3044\u3002
postgresql.con.auth:\u8A8D\u8A3C\u30BF\u30A4\u30D7 {0} \u306F\u30B5\u30DD\u30FC\u30C8\u3055\u308C\u3066\u3044\u307E\u305B\u3093\u3002 Check that you have configured the pg_hba.conf file to include the client's IP address or Subnet, and that it is using an authentication scheme supported by the driver.
postgresql.con.authfail:\u8A8D\u8A3C\u30EA\u30AF\u30A8\u30B9\u30C8\u3092\u53D6\u5F97\u3057\u3088\u3046\u3068\u3057\u3066\u30A8\u30E9\u30FC\u304C\u767A\u751F\u3057\u307E\u3057\u305F\u3002
postgresql.con.backend:\u30D0\u30C3\u30AF\u30A8\u30F3\u30C9\u306E\u958B\u59CB\u306B\u5931\u6557\u3057\u307E\u3057\u305F: {0}
postgresql.con.call:\u547C\u3073\u51FA\u3057\u53EF\u80FD\u306A\u30B9\u30C6\u30FC\u30C8\u30E1\u30F3\u30C8\u306F\u3053\u306E\u6642\u30B5\u30DD\u30FC\u30C8\u3055\u308C\u307E\u305B\u3093\u3002
postgresql.con.invalidchar:\u7121\u52B9\u306A\u6587\u5B57\u30C7\u30FC\u30BF\u304C\u3042\u308A\u307E\u3057\u305F\u3002 This is most likely caused by stored data containing characters that are invalid for the character set the database was created in.  The most common example of this is storing 8bit data in a SQL_ASCII database.
postgresql.con.closed:Connection \u306F\u9589\u3058\u3089\u308C\u3066\u3044\u307E\u3059\u3002 \u51E6\u7406\u3092\u7D9A\u884C\u3059\u308B\u3053\u3068\u304C\u3067\u304D\u307E\u305B\u3093\u3002
postgresql.con.creobj:\u30AA\u30D6\u30B8\u30A7\u30AF\u30C8\u306E\u4F5C\u6210\u306B\u5931\u6557\u3057\u307E\u3057\u305F for {0} {1}
postgresql.con.failed:\u63A5\u7D9A\u306E\u8A66\u307F\u306F\u5931\u6557\u3057\u307E\u3057\u305F because {0}
postgresql.con.failed.bad.encoding:\u30B5\u30FC\u30D0\u306E\u30A8\u30F3\u30B3\u30FC\u30C7\u30A3\u30F3\u30B0\u306E\u53D6\u5F97\u3092\u8A66\u307F\u305F\u63A5\u7D9A\u306F\u5931\u6557\u3057\u307E\u3057\u305F\u3002
postgresql.con.failed.bad.autocommit:autocommit\u30B9\u30C6\u30FC\u30BF\u30B9\u306E\u53D6\u5F97\u3092\u8A66\u307F\u305F\u63A5\u7D9A\u306F\u5931\u6557\u3057\u307E\u3057\u305F\u3002
postgresql.con.fathom:update count {0} \u3092\u63A8\u6E2C\u3067\u304D\u307E\u305B\u3093\u3002
postgresql.con.garbled:\u8AA4\u3063\u305F\u30C7\u30FC\u30BF\u3092\u53D7\u3051\u53D6\u308A\u307E\u3057\u305F\u3002
postgresql.con.ioerror:\u30D0\u30C3\u30AF\u30A8\u30F3\u30C9\u3078\u306E\u9001\u4FE1\u3067IO \u30A8\u30E9\u30FC\u304C\u767A\u751F\u3057\u307E\u3057\u305F  - {0}
postgresql.con.kerb4:\u3053\u306E\u30C9\u30E9\u30A4\u30D0\u3067\u306FKerberos 4 \u8A8D\u8A3C\u3092\u30B5\u30DD\u30FC\u30C8\u3057\u3066\u3044\u307E\u305B\u3093\u3002
postgresql.con.kerb5:\u3053\u306E\u30C9\u30E9\u30A4\u30D0\u3067\u306FKerberos 5 \u8A8D\u8A3C\u3092\u30B5\u30DD\u30FC\u30C8\u3057\u3066\u3044\u307E\u305B\u3093\u3002
postgresql.con.misc:\u30B3\u30CD\u30AF\u30B7\u30E7\u30F3\u30FB\u30A8\u30E9\u30FC\u304C\u767A\u751F\u3057\u307E\u3057\u305F: {0}
postgresql.con.multres:\u8907\u6570\u306Eresult\u30B0\u30EB\u30FC\u30D7\u3092\u6271\u3046\u3053\u3068\u306F\u3067\u304D\u307E\u305B\u3093\u3002
postgresql.con.pass:password \u30D7\u30ED\u30D1\u30C6\u30A3\u304C\u898B\u3064\u304B\u308A\u307E\u305B\u3093\u3002 \u5FC5\u9808\u9805\u76EE\u3067\u3059\u3002
postgresql.con.refused:\u63A5\u7D9A\u306F\u62D2\u5426\u3055\u308C\u307E\u3057\u305F\u3002\u30DB\u30B9\u30C8\u540D\u3068\u30DD\u30FC\u30C8\u756A\u53F7\u304C\u6B63\u3057\u3044\u304B\u3001postmaster\u304CTCP/IP\u63A5\u7D9A\u3092\u8A31\u53EF\u3057\u3066\u3044\u308B\u304B\u3069\u3046\u304B\u78BA\u8A8D\u3057\u3066\u304F\u3060\u3055\u3044\u3002
postgresql.con.scm:\u3053\u306E\u30C9\u30E9\u30A4\u30D0\u306FSCM \u8A3C\u660E\u66F8\u306B\u3088\u308B\u8A8D\u8A3C\u3092\u30B5\u30DD\u30FC\u30C8\u3057\u3066\u3044\u307E\u305B\u3093\u3002
postgresql.con.setup:\u30D7\u30ED\u30C8\u30B3\u30EB\u30A8\u30E9\u30FC\u3002\u30BB\u30C3\u30B7\u30E7\u30F3\u306E\u8A2D\u5B9A\u306B\u5931\u6557\u3057\u307E\u3057\u305F\u3002
postgresql.con.sslfail:SSL\u30B3\u30CD\u30AF\u30B7\u30E7\u30F3\u306E\u8A2D\u5B9A\u3092\u53D6\u5F97\u3057\u3088\u3046\u3068\u3057\u3066\u30A8\u30E9\u30FC\u304C\u767A\u751F\u3057\u307E\u3057\u305F\u3002
postgresql.con.sslnotsupported:\u30B5\u30FC\u30D0\u306F SSL\u3092\u30B5\u30DD\u30FC\u30C8\u3057\u3066\u3044\u307E\u305B\u3093\u3002
postgresql.con.strobj:\u30AA\u30D6\u30B8\u30A7\u30AF\u30C8\u3092\u683C\u7D0D\u3059\u308B\u3053\u3068\u304C\u3067\u304D\u307E\u305B\u3093\u3002\u5FC5\u8981\u306A\u30C6\u30FC\u30D6\u30EB\u304C\u30C7\u30FC\u30BF\u30D9\u30FC\u30B9\u4E2D\u306B\u4F5C\u6210\u3055\u308C\u3066\u3044\u308B\u304B\u78BA\u8A8D\u3057\u3066\u304F\u3060\u3055\u3044\u3002
postgresql.con.strobjex:\u30AA\u30D6\u30B8\u30A7\u30AF\u30C8\u306E\u683C\u7D0D\u306B\u5931\u6557\u3057\u307E\u3057\u305F - {0}
postgresql.con.toolong:SQL\u30B9\u30C6\u30FC\u30C8\u30E1\u30F3\u30C8\u306F\u9577\u3059\u304E\u307E\u3059 - {0}
postgresql.con.isolevel:\u30C8\u30E9\u30F3\u30B6\u30AF\u30B7\u30E7\u30F3\u9694\u96E2\u30EC\u30D9\u30EB {0} \u306F\u30B5\u30DD\u30FC\u30C8\u3055\u308C\u3066\u3044\u307E\u305B\u3093\u3002
postgresql.con.tuple:MetaData\u306E\u524D\u306BTuple\u3092\u53D7\u4FE1\u3057\u307E\u3057\u305F\u3002
postgresql.con.type:\u4E0D\u660E\u306A\u30EC\u30B9\u30DD\u30F3\u30B9\u578B {0}
postgresql.con.user:user \u30D7\u30ED\u30D1\u30C6\u30A3\u304C\u3042\u308A\u307E\u305B\u3093\u3002\u5FC5\u9808\u9805\u76EE\u3067\u3059\u3002
postgresql.error.detail:Detail: {0}
postgresql.error.hint:Hint: {0}
postgresql.error.position:Position: {0}
postgresql.error.where:Where: {0}
postgresql.error.location:Location: {0}
postgresql.fp.error:FastPath call returned {0}
postgresql.fp.expint:Fastpath call {0} - No result was returned and we expected an integer.
postgresql.fp.protocol:FastPath \u30D7\u30ED\u30C8\u30B3\u30EB\u30FB\u30A8\u30E9\u30FC: {0}
postgresql.fp.send:Failed to send fastpath call {0} {1}
postgresql.fp.unknown:The fastpath function {0} is unknown.
postgresql.geo.box:box\u306E\u5909\u63DB\u306B\u5931\u6557\u3057\u307E\u3057\u305F - {0}
postgresql.geo.circle:circle \u306E\u5909\u63DB\u306B\u5931\u6557\u3057\u307E\u3057\u305F - {0}
postgresql.geo.line:line\u306E\u5909\u63DB\u306B\u5931\u6557\u3057\u307E\u3057\u305F - {0}
postgresql.geo.lseg:lseg \u306E\u5909\u63DB\u306B\u5931\u6557\u3057\u307E\u3057\u305F - {0}
postgresql.geo.path:path\u304C\u958B\u3044\u3066\u3044\u308B\u304B\u9589\u3058\u3066\u3044\u308B\u304B\u308F\u304B\u308A\u307E\u305B\u3093\u3002
postgresql.geo.point:point \u306E\u5909\u63DB\u306B\u5931\u6557\u3057\u307E\u3057\u305F - {0}
postgresql.jvm.version:postgresql.jar \u30D5\u30A1\u30A4\u30EB\u306F\u3053\u306EJVM\u306E\u305F\u3081\u306E\u6B63\u3057\u3044JDBC\u30AF\u30E9\u30B9\u3092\u542B\u3093\u3067\u3044\u307E\u305B\u3093\u3002 \u518D\u69CB\u7BC9\u3057\u3066\u304F\u3060\u3055\u3044\u3002\u3082\u3057\u5931\u6557\u3059\u308B\u5834\u5408\u3001\u30B3\u30DE\u30F3\u30C9\u30E9\u30A4\u30F3\u306B -Djava.version=1.1 \u307E\u305F\u306F -Djava.version=1.2\u306E\u5F15\u6570\u3092\u4F7F\u3063\u3066\u4F9B\u7D66\u30D0\u30FC\u30B8\u30E7\u30F3\u3092\u5F37\u8981\u3057\u3066\u307F\u3066\u304F\u3060\u3055\u3044\nException thrown was {0}
postgresql.lo.init:LargeObject API\u306E\u521D\u671F\u5316\u306B\u5931\u6557\u3057\u307E\u3057\u305F\u3002
postgresql.metadata.unavailable:Metadata \u304C\u5229\u7528\u3067\u304D\u307E\u305B\u3093\u3002
postgresql.money:\u30E1\u30E2\u30EA\u30FC\u306E\u5909\u63DB\u306B\u5931\u6557\u3057\u307E\u3057\u305F - {0}
postgresql.noupdate:\u3053\u306E ResultSet \u306Fupdate\u3067\u304D\u307E\u305B\u3093\u3002
postgresql.notsensitive:\u3053\u306E ResultSet \u306F\u30AF\u30A8\u30EA\u30FC\u5B9F\u884C\u5F8C\u306E\u30EA\u30A2\u30EB\u30BF\u30A4\u30E0\u66F4\u65B0\u306E\u5F71\u97FF\u306F\u53D7\u3051\u307E\u305B\u3093\u3002
postgresql.psqlnotimp:\u30D0\u30C3\u30AF\u30A8\u30F3\u30C9\u306F\u73FE\u5728\u3053\u306E\u51E6\u7406\u3092\u30B5\u30DD\u30FC\u30C8\u3057\u3066\u3044\u307E\u305B\u3093\u3002
postgresql.prep.is:parameter \u306EInputStream\u306F\u30B5\u30DD\u30FC\u30C8\u3055\u308C\u307E\u305B\u3093\u3002
postgresql.prep.param:\u30D1\u30E9\u30E1\u30FC\u30BF {0} \u306E\u5024\u304C\u6307\u5B9A\u3055\u308C\u3066\u3044\u307E\u305B\u3093\u3002
postgresql.prep.range:\u30D1\u30E9\u30E1\u30FC\u30BF\u306E\u6DFB\u5B57\u304C\u6307\u5B9A\u3067\u304D\u308B\u7BC4\u56F2\u3092\u8D85\u3048\u3066\u3044\u307E\u3059\u3002
postgresql.prep.type:\u4E0D\u660E\u306A\u578B\u306E\u5024\u3067\u3059\u3002
postgresql.res.badbigdec:{0} \u306F BigDecimal\u3067\u306F\u3042\u308A\u307E\u305B\u3093\u3002
postgresql.res.badbyte:{0} \u306FByte\u3067\u306F\u3042\u308A\u307E\u305B\u3093\u3002
postgresql.res.baddate:{1}\u306E{0}\u306F\u6B63\u3057\u3044 Date Format \u3067\u306F\u3042\u308A\u307E\u305B\u3093\u3002
postgresql.res.baddouble:{0} \u306Fdouble\u3067\u306F\u3042\u308A\u307E\u305B\u3093\u3002
postgresql.res.badfloat:{0}\u306FFloat\u3067\u306F\u3042\u308A\u307E\u305B\u3093\u3002
postgresql.res.badint:{0}\u306FInteger\u3067\u306F\u3042\u308A\u307E\u305B\u3093\u3002
postgresql.res.badlong:{0}\u306FLong\u3067\u306F\u3042\u308A\u307E\u305B\u3093\u3002
postgresql.res.badshort:{0}\u306FShort\u3067\u306F\u3042\u308A\u307E\u305B\u3093\u3002
postgresql.res.badtime:{0}\u306FTime\u3067\u306F\u3042\u308A\u307E\u305B\u3093\u3002
postgresql.res.badtimestamp:{1}\u306E{0}\u306F\u6B63\u3057\u304F\u306A\u3044 Timestamp \u30D5\u30A9\u30FC\u30DE\u30C3\u30C8\u3067\u3059\u3002
postgresql.res.closed:Result set \u306F\u9589\u3058\u3066\u3044\u307E\u3059\u3002\u51E6\u7406\u3059\u308B\u3053\u3068\u304C\u3067\u304D\u307E\u305B\u3093\u3002
postgresql.res.colname:\u30AB\u30E9\u30E0\u540D {0} \u306F\u5B58\u5728\u3057\u307E\u305B\u3093\u3002
postgresql.res.colrange:\u30AB\u30E9\u30E0\u306E\u6DFB\u5B57\u304C\u6307\u5B9A\u53EF\u80FD\u306A\u7BC4\u56F2\u3092\u8D85\u3048\u3066\u3044\u307E\u3059\u3002
postgresql.res.nextrequired:Result set \u304C\u6B63\u3057\u3044\u4F4D\u7F6E\u306B\u3042\u308A\u307E\u305B\u3093\u3002\u304A\u305D\u3089\u304F next()\u3092call\u3059\u308B\u5FC5\u8981\u304C\u3042\u308A\u307E\u3059\u3002
postgresql.serial.interface:\u30A4\u30F3\u30BF\u30FC\u30D5\u30A7\u30FC\u30B9\u3092\u76F4\u5217\u5316\u3059\u308B\u3053\u3068\u306F\u3067\u304D\u307E\u305B\u3093\u3002
postgresql.serial.namelength:Class & Package \u540D\u306E\u9577\u3055\u306F64\u6587\u5B57\u3088\u308A\u9577\u304F\u3059\u308B\u3053\u3068\u306F\u3067\u304D\u307E\u305B\u3093\u3002 {0}\u306F{1}\u6587\u5B57\u3067\u3059\u3002
postgresql.serial.noclass:\u30AF\u30E9\u30B9\u304C\u3042\u308A\u307E\u305B\u3093 for {0}
postgresql.serial.table:{0}\u306E\u30C6\u30FC\u30D6\u30EB\u306F\u30C7\u30FC\u30BF\u30D9\u30FC\u30B9\u4E2D\u306B\u3042\u308A\u307E\u305B\u3093\u3002 Contact the DBA, as the database is in an inconsistent state.
postgresql.serial.underscore:Class names may not have _ in them. You supplied {0}.
postgresql.stat.batch.error:Batch entry {0} {1} was aborted. Call getNextException() to see the cause.
postgresql.stat.noresult:query\u306B\u5BFE\u3059\u308B result \u304C\u8FD4\u3063\u3066\u304D\u307E\u305B\u3093\u3067\u3057\u305F\u3002
postgresql.stat.result:\u4E88\u671F\u3057\u306A\u3044\u6642\u306Bresult\u304C\u8FD4\u3055\u308C\u307E\u3057\u305F\u3002
postgresql.stream.eof:\u30D0\u30C3\u30AF\u30A8\u30F3\u30C9\u306F\u63A5\u7D9A\u3092\u4E2D\u65AD\u3057\u307E\u3057\u305F\u3002 Possibly the action you have attempted has caused it to close.
postgresql.stream.flush:\u51FA\u529B\u3092flush\u3059\u308B\u3068\u304D\u306BI/O\u30A8\u30E9\u30FC\u304C\u767A\u751F\u3057\u307E\u3057\u305F - {0}
postgresql.stream.ioerror:\u30D0\u30C3\u30AF\u30A8\u30F3\u30C9\u304B\u3089\u306E\u8AAD\u8FBC\u307F\u3067 I/O\u30A8\u30E9\u30FC\u304C\u767A\u751F\u3057\u307E\u3057\u305F\u3002 - {0}
postgresql.stream.toomuch:\u591A\u3059\u304E\u308B\u30C7\u30FC\u30BF\u3092\u53D7\u4FE1\u3057\u307E\u3057\u305F\u3002
postgresql.unusual:\u901A\u5E38\u8D77\u304D\u306A\u3044\u7570\u5E38\u304C\u30C9\u30E9\u30A4\u30D0\u3092\u5931\u6557\u3055\u305B\u307E\u3057\u305F\u3002\u3053\u306E\u4F8B\u5916\u3092\u5831\u544A\u3057\u3066\u304F\u3060\u3055\u3044: {0}
postgresql.unimplemented:\u3053\u306E\u30E1\u30BD\u30C3\u30C9\u306F\u307E\u3060\u5B9F\u88C5\u3055\u308C\u3066\u3044\u307E\u305B\u3093\u3002
postgresql.unexpected:query\u306B\u5BFE\u3059\u308B\u4E88\u671F\u3057\u306A\u3044result\u304C\u8FD4\u3063\u3066\u304D\u307E\u3057\u305F\u3002
postgresql.updateable.notupdateable: \u66F4\u65B0\u53EF\u80FD\u306AResult Set \u3067\u306F\u3042\u308A\u307E\u305B\u3093\u3002\u3053\u306Eresult set\u3092\u751F\u6210\u3057\u305Fquery\u306F1\u3064\u3060\u3051\u306Etable\u3092select\u3057\u3001\u305D\u306E\u30C6\u30FC\u30D6\u30EB\u306E\u5168\u3066\u306E\u4E3B\u30AD\u30FC\u3092select\u3057\u305F\u3082\u306E\u3067\u306A\u3051\u308C\u3070\u306A\u308A\u307E\u305B\u3093\u3002\u8A73\u7D30\u306F JDBC 2.1 API \u4ED5\u69D8, section 5.6 \u3092\u53C2\u7167\u3057\u3066\u304F\u3060\u3055\u3044\u3002
postgresql.updateable.oninsertrow:insert row\u4E0A\u3067 deleteRow() \u3092\u547C\u3073\u51FA\u3059\u3053\u3068\u306F\u3067\u304D\u307E\u305B\u3093\u3002
postgresql.updateable.emptydelete:\u7A7A\u306E result set \u306B deleteRow() \u3059\u308B\u3053\u3068\u306F\u3067\u304D\u307E\u305B\u3093\u3002
postgresql.updateable.beforestartdelete:result set\u306Estart\u306E\u524D\u3067 deleteRow()\u3092\u547C\u3073\u51FA\u3059\u3053\u3068\u306F\u3067\u304D\u307E\u305B\u3093\u3002
postgresql.updateable.afterlastdelete:result set\u306Eend\u306E\u5F8C\u3067 deleteRow()\u3092\u547C\u3073\u51FA\u3059\u3053\u3068\u306F\u3067\u304D\u307E\u305B\u3093\u3002
postgresql.updateable.notoninsertrow:Not on insert row.
postgresql.updateable.inputstream:Input Stream \u306F null\u3067\u3059\u3002
postgresql.updateable.ioerror:Input Stream \u30A8\u30E9\u30FC - {0}
postgresql.call.noreturntype:A CallableStatement Function was declared but no call to 'registerOutParameter (1, <some_type>)' was made.
postgresql.call.noinout:PostgreSQL only supports function return value [@ 1] (no OUT or INOUT arguments)
postgresql.call.procasfunc:This Statement [{0}] defines a procedure call (needs ?= call <stmt> to be considered a function.
postgresql.call.malformed:Malformed stmt [{0}] usage : {1}
postgresql.call.funcover:Cannot execute Query a call to setXXX (1, ..) was made where argument 1 is the return value of a function.
postgresql.call.wrongget:Parameter of type {0} was registered but call to get{1} (sqltype={2}) was made.
postgresql.call.noreturnval:A CallableStatement Function was executed with nothing returned.
postgresql.call.wrongrtntype:A CallableStatement Function was executed and the return was of type ({0}) however type={1} was registered.
postgresql.input.fetch.gt0:Fetch size \u306F0\u4EE5\u4E0A\u306E\u5024\u3067\u306A\u3051\u308C\u3070\u306A\u308A\u307E\u305B\u3093\u3002
postgresql.input.query.gt0:Query Timeout \u306F0\u4EE5\u4E0A\u306E\u5024\u3067\u306A\u3051\u308C\u3070\u306A\u308A\u307E\u305B\u3093\u3002
postgresql.input.rows.gt0:Maximum number of rows \u306F0\u4EE5\u4E0A\u306E\u5024\u3067\u306A\u3051\u308C\u3070\u306A\u308A\u307E\u305B\u3093\u3002
postgresql.format.baddate:\u6E21\u3055\u308C\u305Fdate: {0} \u306F\u5FC5\u8981\u306A {1}\u306E\u30D5\u30A9\u30FC\u30DE\u30C3\u30C8\u3068\u4E00\u81F4\u3057\u307E\u305B\u3093\u3002
postgresql.format.badtime:\u5165\u529B\u3055\u308C\u305Ftime {0}\u306F\u5FC5\u8981\u306A{1}\u306E\u30D5\u30A9\u30FC\u30DE\u30C3\u30C8\u3068\u4E00\u81F4\u3057\u307E\u305B\u3093\u3002
postgresql.format.badtimestamp:The timestamp given {0} does not match the format required: {1}.
postgresql.input.field.gt0:maximum field size \u306F0\u4EE5\u4E0A\u306E\u5024\u3067\u306A\u3051\u308C\u3070\u306A\u308A\u307E\u305B\u3093\u3002
